# nixpacks.toml

[phases.setup]
providers = ["nodejs", "caddy"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmd = "caddy run --config /app/Caddyfile --adapter caddyfile" 