# nixpacks.toml

[phases.setup]
providers = ["nodejs", "caddy"]
nixPkgs = ["coreutils"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
    "npm run build",
    "chmod +x start.sh"
]

[phases.start]
cmd = "./start.sh" 