# nixpacks.toml

[phases.setup]
providers = ["nodejs", "caddy"]
nixPkgs = ["coreutils"]
aptPkgs = ["nodejs", "npm"]

[phases.install]
cmds = [
    "npm install -g npm@latest",
    "npm ci"
]

[phases.build]
cmds = [
    "npm run build",
    "chmod +x start.sh"
]

[start]
cmd = "./start.sh" 